In [1]:
import numpy as np
import pandas as pd
import scipy.stats as ss
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Meiryo'
#plt.rcParams['font.family'] = 'Hiragino Sans' # for macOS

In [2]:
df = pd.read_csv("j_points.csv",delimiter=",",encoding="UTF-8")
display(df.head()) 
print(df.dtypes) 
print(df.shape)
display(df.head())

,team,cross_point,goal_point,shoot_point,dribble_point,pass_point,attack
0,横浜F・マリノス,25.45,47.98,84.18,11.70,143.10,180.25
1,浦和レッズ,22.88,23.71,77.92,11.09,112.26,146.23
2,アビスパ福岡,21.06,8.56,43.92,11.93,78.90,111.90
3,鹿島アントラーズ,18.57,35.24,74.36,15.67,106.93,141.17
4,サガン鳥栖,17.72,20.37,37.50,6.85,111.70,136.28

team              object
cross_point      float64
goal_point       float64
shoot_point      float64
dribble_point    float64
pass_point       float64
attack           float64
dtype: object
(18, 7)

,team,cross_point,goal_point,shoot_point,dribble_point,pass_point,attack
0,横浜F・マリノス,25.45,47.98,84.18,11.70,143.10,180.25
1,浦和レッズ,22.88,23.71,77.92,11.09,112.26,146.23
2,アビスパ福岡,21.06,8.56,43.92,11.93,78.90,111.90
3,鹿島アントラーズ,18.57,35.24,74.36,15.67,106.93,141.17
4,サガン鳥栖,17.72,20.37,37.50,6.85,111.70,136.28